source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

inhibit_all_warnings!
pod 'PureLayout'
pod 'pop', '~> 1.0'

target 'TabBarPicker_Example', :exclusive => true do
  pod "TabBarPicker", :path => "../"
end

target 'TabBarPicker_Tests', :exclusive => true do
  pod "TabBarPicker", :path => "../"
end


