source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TabBarPicker_Example', :exclusive => true do
  pod "TabBarPicker", :path => "../"
end

target 'TabBarPicker_Tests', :exclusive => true do
  pod "TabBarPicker", :path => "../"

  pod 'FBSnapshotTestCase'
  pod 'PureLayout'
  pod 'pop', '~> 1.0'
end
